FROM public.ecr.aws/lambda/nodejs@sha256:ba6eb28e407ede3f5d8ab441aadd4ad7558cfdb099f324f195d1f6ddc885d4bf AS deps

# Lambda workdir chuẩn
WORKDIR /var/task

# NOTE: Cần chạy build từ root
COPY src/teacher-service/package*.json .

RUN npm ci

FROM public.ecr.aws/lambda/nodejs@sha256:ba6eb28e407ede3f5d8ab441aadd4ad7558cfdb099f324f195d1f6ddc885d4bf AS builder

WORKDIR /var/task

COPY --from=deps /var/task/node_modules ./node_modules

COPY src/teacher-service/ .
COPY src/shared-libs ./shared-libs

# Generate Prisma client
RUN npx prisma generate

# Bỏ devDependencies và xóa cache npm
RUN npm prune --omit=dev && npm cache clean --force

FROM public.ecr.aws/lambda/nodejs@sha256:ba6eb28e407ede3f5d8ab441aadd4ad7558cfdb099f324f195d1f6ddc885d4bf AS runner

WORKDIR /var/task

COPY --from=builder /var/task .

# APP_ENV test AWS infra local
ENV NODE_ENV=production
ENV APP_ENV=production

# Lambda handler
CMD ["server.handler"]