FROM public.ecr.aws/lambda/nodejs@sha256:ba6eb28e407ede3f5d8ab441aadd4ad7558cfdb099f324f195d1f6ddc885d4bf AS builder

# Lambda workdir chuẩn
WORKDIR /var/task

COPY src/auth-service/package*.json .

# Không cài devDependencies và xóa cache npm
RUN npm ci --omit=dev && npm cache clean --force

COPY src/auth-service/ .
COPY src/shared-libs/ ./shared-libs

FROM public.ecr.aws/lambda/nodejs@sha256:ba6eb28e407ede3f5d8ab441aadd4ad7558cfdb099f324f195d1f6ddc885d4bf AS runner

WORKDIR /var/task

COPY --from=builder /var/task .

# APP_ENV test AWS infra local
ENV NODE_ENV=production
ENV APP_ENV=production

# Lambda handler
CMD ["server.handler"]