name: Action CI build

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/.dockerignore'
      - '**/.gitignore'
      - '**/Dockerfile'
      - '/docs/**'
  workflow_dispatch:

jobs:
  build-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup & cache
        uses: ./.github/setup-deps
        with:
          context: ./auth-service
      
  build-student:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup & cache
        uses: ./.github/setup-deps
        with:
          context: ./student-service

  build-class:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup & cache
        uses: ./.github/setup-deps
        with:
          context: ./class-service